# Generated by Django 4.2 on 2023-05-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0002_issuebooks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuebooks',
            name='student_id',
        ),
        migrations.AddField(
            model_name='book',
            name='uid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=200, verbose_name='Author name'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cat',
            field=models.CharField(choices=[('1', 'Fantacy'), ('2', 'Adventure'), ('3', 'Historical'), ('4', 'Horror'), ('5', 'Triller')], max_length=200, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=200, verbose_name='book name'),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('0', 'Inactive')], max_length=100),
        ),
        migrations.AlterField(
            model_name='issuebooks',
            name='Student_name',
            field=models.CharField(max_length=100, verbose_name='Student name'),
        ),
        migrations.AlterField(
            model_name='issuebooks',
            name='issued_date',
            field=models.DateField(),
        ),
    ]
