# Generated by Django 4.2 on 2023-05-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0003_remove_issuebooks_student_id_book_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebooks',
            name='uid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
